### ISSUE TITLE
Modelscope_Faster_Whisper_Multi_Subtitle/output/video.srt

### ISSUE THREAD

**Issue by lipingle** [v3ucn/Modelscope_Faster_Whisper_Multi_Subtitle#17]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/gradio/routes.py", line 412, in run_predict
    output = await app.get_blocks().process_api(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1299, in process_api
    result = await self.call_function(
  File "/usr/local/lib/python3.10/dist-packages/gradio/blocks.py", line 1021, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/dist-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/dist-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/home/video/Modelscope_Faster_Whisper_Multi_Subtitle/app.py", line 61, in do_trans_en2zh_deep
    return make_tran_deep(srt_path,"EN","ZH")
  File "/home/video/Modelscope_Faster_Whisper_Multi_Subtitle/utils.py", line 309, in make_tran_deep
    with open(srt_path, 'r',encoding="utf-8") as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/video/Modelscope_Faster_Whisper_Multi_Subtitle/output/video.srt'

**Comment by lipingle** [comment]
手动创建就好
