### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by xingforce** [v3ucn/Modelscope_Faster_Whisper_Multi_Subtitle#18]
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/py309-ms/lib/python3.9/site-packages/pyttsx3/__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "/opt/homebrew/anaconda3/envs/py309-ms/lib/python3.9/weakref.py", line 137, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xing/make-tools/Modelscope_Faster_Whisper_Multi_Subtitle/app.py", line 12, in <module>
    from subtitle_to_audio import generate_audio
  File "/Users/xing/make-tools/Modelscope_Faster_Whisper_Multi_Subtitle/subtitle_to_audio.py", line 9, in <module>
    engine = pyttsx3.init()
  File "/opt/homebrew/anaconda3/envs/py309-ms/lib/python3.9/site-packages/pyttsx3/__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "/opt/homebrew/anaconda3/envs/py309-ms/lib/python3.9/site-packages/pyttsx3/engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "/opt/homebrew/anaconda3/envs/py309-ms/lib/python3.9/site-packages/pyttsx3/driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
  File "/opt/homebrew/anaconda3/envs/py309-ms/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/homebrew/anaconda3/envs/py309-ms/lib/python3.9/site-packages/pyttsx3/drivers/nsss.py", line 12, in <module>
    class NSSpeechDriver(NSObject):
  File "/opt/homebrew/anaconda3/envs/py309-ms/lib/python3.9/site-packages/pyttsx3/drivers/nsss.py", line 13, in NSSpeechDriver
    @objc.python_method
NameError: name 'objc' is not defined

**Comment by v3ucn** [comment]
pip3 install -U pyttsx3
