### ISSUE TITLE
修正版中译英加载模型报错OSError: ./models_from_modelscope\damo\nlp_csanmt_translation_en2zh does not appear to have a file named config.json. Checkout 'https://huggingface.co/./models_from_modelscope\damo\nlp_csanmt_translation_en2zh/None' for available files.

### ISSUE THREAD

**Issue by hyhuc0079** [v3ucn/Modelscope_Faster_Whisper_Multi_Subtitle#3]
我看要不直接在read me里提供haggingface地址让用户自己去下吧？
另外支持damo的其他语种模型吗?
做成用户自己填模型字段自己去下对应语种模型如何

错误信息粘贴给你

Traceback (most recent call last):
  File "D:\ai2vedio\Modelscope_Faster_Whisper_Multi_Subtitle\venv\lib\site-packages\gradio\routes.py", line 534, in predict
    output = await route_utils.call_process_api(
  File "D:\ai2vedio\Modelscope_Faster_Whisper_Multi_Subtitle\venv\lib\site-packages\gradio\route_utils.py", line 226, in call_process_api
    output = await app.get_blocks().process_api(
  File "D:\ai2vedio\Modelscope_Faster_Whisper_Multi_Subtitle\venv\lib\site-packages\gradio\blocks.py", line 1550, in process_api
    result = await self.call_function(
  File "D:\ai2vedio\Modelscope_Faster_Whisper_Multi_Subtitle\venv\lib\site-packages\gradio\blocks.py", line 1185, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\ai2vedio\Modelscope_Faster_Whisper_Multi_Subtitle\venv\lib\site-packages\anyio\to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "D:\ai2vedio\Modelscope_Faster_Whisper_Multi_Subtitle\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 2134, in run_sync_in_worker_thread
    return await future
  File "D:\ai2vedio\Modelscope_Faster_Whisper_Multi_Subtitle\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 851, in run
    result = context.run(func, *args)
  File "D:\ai2vedio\Modelscope_Faster_Whisper_Multi_Subtitle\venv\lib\site-packages\gradio\utils.py", line 661, in wrapper
    response = f(*args, **kwargs)
  File "D:\ai2vedio\Modelscope_Faster_Whisper_Multi_Subtitle\Modelscope_Faster_Whisper_Multi_Subtitle\app.py", line 40, in do_trans_en2zh
    return make_tran()
  File "D:\ai2vedio\Modelscope_Faster_Whisper_Multi_Subtitle\Modelscope_Faster_Whisper_Multi_Subtitle\utils.py", line 119, in make_tran
    pipeline_ins = pipeline(task=Tasks.translation, model=model_dir_ins)
  File "D:\ai2vedio\Modelscope_Faster_Whisper_Multi_Subtitle\venv\lib\site-packages\transformers\pipelines\__init__.py", line 782, in pipeline
    config = AutoConfig.from_pretrained(
  File "D:\ai2vedio\Modelscope_Faster_Whisper_Multi_Subtitle\venv\lib\site-packages\transformers\models\auto\configuration_auto.py", line 1082, in from_pretrained
    config_dict, unused_kwargs = PretrainedConfig.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "D:\ai2vedio\Modelscope_Faster_Whisper_Multi_Subtitle\venv\lib\site-packages\transformers\configuration_utils.py", line 644, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "D:\ai2vedio\Modelscope_Faster_Whisper_Multi_Subtitle\venv\lib\site-packages\transformers\configuration_utils.py", line 699, in _get_config_dict
    resolved_config_file = cached_file(
  File "D:\ai2vedio\Modelscope_Faster_Whisper_Multi_Subtitle\venv\lib\site-packages\transformers\utils\hub.py", line 360, in cached_file
    raise EnvironmentError(

+++++++++++++++++++++++++++我是分割线别理我+++++++++++
OSError: ./models_from_modelscope\damo\nlp_csanmt_translation_en2zh does not appear to have a file named config.json. Checkout 'https://huggingface.co/./models_from_modelscope\damo\nlp_csanmt_translation_en2zh/None' for available files.
+++++++++++++++++++++++++++我是分割线别理我+++++++++++

**Comment by txs** [comment]
我也遇到這個問題 OSError: ./models_from_modelscope/damo/nlp_csanmt_translation_en2zh does not appear to have a file named config.json. Checkout 'https://huggingface.co/./models_from_modelscope/damo/nlp_csanmt_translation_en2zh/None' for available files.
